#	@(#)Makefile	5.2 (Berkeley) 9/1/92

PROG=	pac
CFLAGS+=-I${.CURDIR}/../common_source
MAN8=	pac.0
SRCS=	pac.c common.c
.PATH:	${.CURDIR}/../common_source

.include "../../Makefile.inc"
.include <bsd.prog.mk>
